import React, { useState } from 'react';
import { Alert, Pressable, View } from 'react-native';
import { Profile, Role, Vehicle } from '../domain/types';
import { useReadyApp } from '../state/AppProvider';
import { Button, Card, common, Field, Header, Icon, Notice, Pill, Row, Screen, Txt } from '../ui/components';
import { colors } from '../ui/theme';

export function ProfileScreen({ onRole }: { onRole: (role: Role) => Promise<void> }) {
  const { state, dispatch, restore } = useReadyApp();
  const [profile, setProfile] = useState<Profile>(state.role === 'owner' ? state.ownerProfile : state.profile);
  const [feedback, setFeedback] = useState('');
  const [vehicleId, setVehicleId] = useState<string | null>(null);
  const [label, setLabel] = useState('');
  const [plate, setPlate] = useState('');
  const [type, setType] = useState<Vehicle['type']>('car');
  const [editing, setEditing] = useState(false);
  const [error, setError] = useState('');
  const saveVehicle = async () => {
    setError('');
    try {
      await dispatch({ type: 'saveVehicle', vehicle: { id: vehicleId ?? `vehicle-${Date.now()}`, label, plate, type } });
      setEditing(false); setVehicleId(null); setLabel(''); setPlate(''); setFeedback('Veículo salvo neste aparelho.');
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível salvar o veículo.'); }
  };
  const reset = () => Alert.alert('Restaurar demonstração?', 'Isso substitui seus cadastros, reservas, avaliações, veículos e preferências pelos dados fictícios iniciais neste aparelho.', [{ text: 'Manter meus dados', style: 'cancel' }, { text: 'Restaurar', style: 'destructive', onPress: () => { void restore().catch(reason => Alert.alert('Falha ao restaurar', String(reason.message))); } }]);
  return <Screen><Header title="Seu perfil" subtitle="Uma conta. Duas possibilidades." /><Card><Row><View style={{ width: 55, height: 55, backgroundColor: colors.orangeLight, alignItems: 'center', justifyContent: 'center', borderRadius: 20 }}><Icon name="user" size={26} /></View><View style={{ flex: 1 }}><Txt variant="heading">{state.role === 'driver' ? state.profile.name : state.ownerProfile.name}</Txt><Txt variant="small" color={colors.muted}>Perfil demonstrativo · salvo localmente</Txt></View></Row><View style={common.wrap}><Pill title="Motorista" icon="navigation" selected={state.role === 'driver'} onPress={() => { void onRole('driver').catch(reason => Alert.alert('Falha ao trocar modo', reason.message)); }} /><Pill title="Proprietário" icon="home" selected={state.role === 'owner'} onPress={() => { void onRole('owner').catch(reason => Alert.alert('Falha ao trocar modo', reason.message)); }} /></View></Card>{!!feedback && <Notice>{feedback}</Notice>}<View style={common.section}><Txt variant="heading">Sobre você</Txt><Field label="Nome demonstrativo" value={profile.name} onChangeText={name => setProfile(p => ({ ...p, name }))} maxLength={80} /><Field label="E-mail (opcional)" value={profile.email} placeholder="voce@exemplo.com" keyboardType="email-address" autoCapitalize="none" onChangeText={email => setProfile(p => ({ ...p, email }))} /><Field label="Telefone (opcional)" value={profile.phone} placeholder="DDD + telefone" keyboardType="phone-pad" maxLength={15} onChangeText={phone => setProfile(p => ({ ...p, phone }))} /><Button title="Salvar perfil" variant="secondary" icon="check" onPress={async () => { await dispatch({ type: 'profile', profile }); setFeedback('Perfil salvo com sucesso.'); }} /></View>
    <View style={common.section}><Txt variant="heading">Meus veículos</Txt><Txt color={colors.muted}>Use dados fictícios para experimentar suas reservas.</Txt>{state.vehicles.map(vehicle => <Card key={vehicle.id}><Row><Icon name={vehicle.type === 'car' ? 'truck' : 'navigation'} /><View style={{ flex: 1 }}><Txt variant="label">{vehicle.label}</Txt><Txt variant="small" color={colors.muted}>{vehicle.plate} · {vehicle.type === 'car' ? 'Carro' : 'Motocicleta'}</Txt></View><Pressable accessibilityRole="button" accessibilityLabel={`Editar ${vehicle.label}`} style={{ padding: 12 }} onPress={() => { setEditing(true); setVehicleId(vehicle.id); setLabel(vehicle.label); setPlate(vehicle.plate); setType(vehicle.type); setError(''); }}><Icon name="edit-2" size={18} /></Pressable><Pressable accessibilityRole="button" accessibilityLabel={`Excluir ${vehicle.label}`} style={{ padding: 12 }} onPress={() => Alert.alert('Excluir veículo?', 'As reservas existentes mantêm seus dados.', [{ text: 'Manter', style: 'cancel' }, { text: 'Excluir', style: 'destructive', onPress: () => { void dispatch({ type: 'deleteVehicle', id: vehicle.id }).then(() => setFeedback('Veículo excluído.')).catch(reason => Alert.alert('Falha ao excluir', reason.message)); } }])}><Icon name="trash-2" color={colors.danger} size={18} /></Pressable></Row></Card>)}
    {editing ? <Card><Txt variant="label">{vehicleId ? 'Editar veículo' : 'Novo veículo'}</Txt><Field label="Modelo e cor" placeholder="Ex.: Onix branco" value={label} onChangeText={setLabel} maxLength={80} /><Field label="Placa" value={plate} onChangeText={setPlate} maxLength={8} autoCapitalize="characters" autoCorrect={false} placeholder="ABC1D23" /><Row><Pill title="Carro" selected={type === 'car'} onPress={() => setType('car')} /><Pill title="Motocicleta" selected={type === 'motorcycle'} onPress={() => setType('motorcycle')} /></Row>{!!error && <Txt color={colors.danger}>{error}</Txt>}<Button title="Salvar veículo" onPress={saveVehicle} /><Button title="Fechar edição" variant="secondary" onPress={() => setEditing(false)} /></Card> : <Button title="Adicionar veículo" icon="plus" variant="secondary" onPress={() => { setEditing(true); setVehicleId(null); setLabel(''); setPlate(''); setError(''); }} />}</View>
    <View style={common.section}><Txt variant="heading">Sobre o Garagem PE</Txt><Notice>Protótipo acadêmico. Dados locais e fictícios. Não há autenticação, cobrança ou transferência financeira.</Notice><Txt variant="small" color={colors.muted}>As alterações ficam apenas neste aparelho. Restaurar a demonstração inicia uma nova experiência com oito vagas em Recife.</Txt><Button title="Restaurar dados demonstrativos" variant="danger" icon="refresh-cw" onPress={reset} /><Txt variant="small" color={colors.muted} style={{ textAlign: 'center' }}>GARAGEM PE · versão 1.0.0</Txt></View></Screen>;
}
