import React from 'react';
import { StyleSheet, View } from 'react-native';
import { amenityLabels, distanceKm, money } from '../../domain/model';
import { useReadyApp } from '../../state/AppProvider';
import { Button, Card, common, Empty, Header, Icon, Notice, Pill, Row, Screen, Txt } from '../../ui/components';
import { colors } from '../../ui/theme';
import { amenityIcons, Favorite, GarageGallery, weekdayNames } from './shared';

function Feature({ title, description, icon }: { title: string; description: string; icon: React.ComponentProps<typeof Icon>['name'] }) {
  return <View style={styles.feature}><View style={styles.featureIcon}><Icon name={icon} size={17} /></View><View style={{ flex: 1, gap: 3 }}><Txt variant="label" style={{ fontSize: 12, lineHeight: 17 }}>{title}</Txt><Txt variant="small" color={colors.muted} style={{ fontSize: 11, lineHeight: 16 }}>{description}</Txt></View></View>;
}

export function GarageDetail({ garageId, onBack, onReserve }: { garageId: string; onBack: () => void; onReserve: () => void }) {
  const { state } = useReadyApp();
  const garage = state.garages.find(item => item.id === garageId);
  if (!garage) return <Screen><Header title="Vaga indisponível" back={onBack} /><Empty title="Vaga não encontrada" description="Volte à busca para encontrar outra vaga." /></Screen>;
  const types = { garage: 'Garagem privada', driveway: 'Entrada privativa', private_lot: 'Pátio privado' };
  const distance = distanceKm(state.preferences.location, garage);
  return <Screen testID="garage-detail"><Header title="Detalhes da vaga" back={onBack} right={<Favorite garage={garage} />} />
    <GarageGallery garage={garage} large />
    <Card style={{ marginTop: garage.photos.length > 1 ? 0 : -45, gap: 16 }}><View style={common.wrap}><View style={styles.authorized}><Icon name={garage.active ? 'check' : 'pause'} size={15} color={colors.success} /><Txt variant="small" color={colors.successText}>{garage.active ? 'Espaço privado autorizado' : 'Anúncio pausado'}</Txt></View></View><Txt variant="heading" style={{ fontSize: 24 }}>{garage.name}</Txt><Txt color={colors.muted}>{garage.neighborhood} · {garage.approximateAddress}</Txt><Row><Icon name="star" color="#B85D00" size={17} /><Txt variant="label">{garage.rating.toLocaleString('pt-BR', { minimumFractionDigits: 1, maximumFractionDigits: 1 })}</Txt><Txt variant="small" color={colors.muted} style={{ flex: 1 }}>· {garage.reviews} avaliações</Txt><View style={styles.distance}><Txt variant="small" color={colors.primary}>{distance.toLocaleString('pt-BR', { maximumFractionDigits: 1 })} km</Txt></View></Row>
      <View style={styles.featureGrid}><Feature icon={garage.amenities.includes('covered') ? 'check' : 'sun'} title={garage.amenities.includes('covered') ? 'Coberta' : 'Descoberta'} description={garage.amenities.includes('covered') ? 'Proteção do sol e chuva' : 'Espaço ao ar livre'} /><Feature icon={garage.amenities.includes('gate') ? 'check' : 'unlock'} title={garage.amenities.includes('gate') ? 'Portão eletrônico' : 'Sem portão eletrônico'} description="Confira as regras de acesso" /><Feature icon="truck" title={garage.vehicleTypes.map(type => type === 'car' ? 'Carro' : 'Moto').join(' e ')} description={`${garage.width.toLocaleString('pt-BR')} m × ${garage.length.toLocaleString('pt-BR')} m`} /><Feature icon="clock" title={garage.availability.opens === '00:00' && garage.availability.closes === '24:00' ? 'Disponível 24h' : `${garage.availability.opens}–${garage.availability.closes}`} description={garage.availability.days.length === 7 ? 'Todos os dias' : 'Veja os dias abaixo'} /></View>
      <View style={common.between}><View style={{ gap: 2 }}><Txt variant="heading" color={colors.primary}>{money(garage.pricePerHour)}</Txt><Txt variant="small" color={colors.muted}>por hora</Txt></View>{state.role === 'driver' && <View style={{ flex: 1, maxWidth: 195 }}><Button title="Reservar vaga" disabled={!garage.active} onPress={onReserve} /></View>}</View>
      {garage.pricePerDay !== null && <Txt variant="small" color={colors.muted}>Diária de até 24h: {money(garage.pricePerDay)}. Comissão incluída.</Txt>}
    </Card>
    <Notice>O endereço completo e as instruções de acesso serão liberados após confirmar a reserva. Local e informações demonstrativos.</Notice>
    <Card><Txt variant="heading">Sobre a vaga</Txt><Txt color={colors.muted}>{garage.description}</Txt><Txt>{types[garage.spaceType]} · {garage.capacity} {garage.capacity === 1 ? 'vaga' : 'vagas'}</Txt><Txt variant="small" color={colors.muted}>Dimensões aproximadas: {garage.width.toLocaleString('pt-BR')} m de largura × {garage.length.toLocaleString('pt-BR')} m de comprimento.</Txt><Txt variant="small" color={colors.muted}>Distância em linha reta de {state.preferences.location.label}.</Txt><View style={common.wrap}>{garage.amenities.filter(amenity => amenity !== 'covered' && amenity !== 'gate').map(amenity => <Pill key={amenity} title={amenityLabels[amenity]} icon={amenityIcons[amenity]} />)}</View><View style={{ gap: 5 }}><Txt variant="small">{garage.amenities.includes('lighting') ? '✓ Iluminação disponível' : '○ Sem iluminação dedicada'}</Txt><Txt variant="small">{garage.amenities.includes('attendant') ? '✓ Responsável presente no local' : '○ Acesso sem responsável presente'}</Txt></View></Card>
    <Card><Txt variant="heading">Horários disponíveis</Txt><View style={common.wrap}>{garage.availability.days.map(day => <Pill key={day} title={weekdayNames[day] ?? ''} />)}</View><Row><Icon name="clock" size={18} /><Txt>{garage.availability.opens} às {garage.availability.closes}</Txt></Row><Txt variant="small" color={colors.muted}>A reserva precisa caber nos períodos disponíveis. A quantidade livre é conferida ao escolher entrada e saída.</Txt></Card>
    <Card><Txt variant="heading">Regras de utilização</Txt><Txt color={colors.muted}>{garage.rules}</Txt></Card>
    <Card><Row><View style={{ width: 44, height: 44, borderRadius: 22, backgroundColor: colors.primaryLight, alignItems: 'center', justifyContent: 'center' }}><Icon name="user" /></View><View style={{ flex: 1 }}><Txt variant="label">{garage.ownerId === 'local' ? state.ownerProfile.name : garage.ownerName}</Txt><Txt variant="small" color={colors.muted}>Proprietário demonstrativo</Txt></View><Icon name="shield" color={colors.primary} /></Row><Txt variant="small" color={colors.muted}>Espaço privado com declaração de responsabilidade e autorização para disponibilização.</Txt></Card>
    <Notice>Comissão de 15% incluída no preço anunciado. Nenhuma cobrança real.</Notice>
    {state.role === 'owner' && <Notice>Você está no modo Proprietário. Para reservar, volte ao perfil e alterne para Motorista.</Notice>}
  </Screen>;
}
const styles = StyleSheet.create({ featureGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, feature: { width: '48%', minHeight: 95, backgroundColor: colors.background, padding: 10, borderRadius: 15, flexDirection: 'row', alignItems: 'flex-start', gap: 7 }, featureIcon: { width: 27, height: 27, borderRadius: 14, backgroundColor: colors.orange, alignItems: 'center', justifyContent: 'center' }, distance: { borderRadius: 13, backgroundColor: colors.primaryLight, paddingHorizontal: 12, paddingVertical: 7 }, authorized: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: colors.successLight, paddingHorizontal: 11, paddingVertical: 6, borderRadius: 14 } });
